bestemmie_list = [
    ' porcodio ',
    ' dioporco ',
    ' bucchin ',
    ' zompaperet ',
    ' porcamadonna ',
    '  dio accecato ',
'  dio affogato nella merda ', 
'  dio aguzzino ',
'  dio ammuffito    ',
'  dio appassito    ',
'  dio appestato    ',
'  dio asino    ',
'  dio asociale ',
'  dio assassino    ',
'  dio assatanato   ',
'  dio ateo  ' ,
'  puttanamadonna  ',
'   puttanalamadonna  ',
'  madonnadiscord. ',
'  diofrocio. ',
'  diocappuccio. ',
'  porcoddio. ' ]